# Generated by Django 3.2.4 on 2021-06-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopers',
            options={'permissions': [('super_acceso', 'Puedes editar todo')]},
        ),
    ]
