# Generated by Django 3.2.4 on 2021-06-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0002_alter_usuariopers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospedaje',
            options={'permissions': [('super_acceso', 'Puedes editar todo')]},
        ),
        migrations.AlterModelOptions(
            name='usuariopers',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
