# Generated by Django 3.2.4 on 2021-06-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0003_auto_20210621_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospedaje',
            options={'permissions': [('add_access', 'Permite agregar registros')]},
        ),
    ]
