# Generated by Django 3.2.4 on 2021-06-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0004_alter_hospedaje_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'permissions': [('usuariocomun', 'Permite a los usarios agregar,editar,eliminar')]},
        ),
    ]
