# Generated by Django 3.2.4 on 2021-06-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0005_alter_vuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'permissions': [('usuarioPerTot', 'Permite a los usarios agregar,editar,eliminar en modelo viaje')]},
        ),
    ]
